replicaCount: 1
image:
  repository: peishu/recommendationservice
  tag: 664817454476b2a95ee73594f5eeb1844fd040f5
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 8080
resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 200m
    memory: 450Mi
