replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/recommendationservice
  tag: v0.1.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 200m
    memory: 450Mi  
