apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recommendationservice.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "recommendationservice.name" . }}
    helm.sh/chart: {{ include "recommendationservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "recommendationservice.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "recommendationservice.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.service.port }}"]
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.service.port }}"]
          env:
          - name: PORT
            value: {{ .Values.service.port | quote }}
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: ENABLE_PROFILER
            value: "0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      